# Generated by Django 4.2.3 on 2023-07-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosterDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=70)),
                ('descricao', models.CharField(max_length=200)),
                ('datapublicacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
